apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAmd5qZlBbEDE1AaDjU8bt9M4aZBmWal1Ao5zY+3KPdkZgC424TGdRjeUxx0g9IbUxP2qBZsg2mWQpdySh32hRlrFtndwZ1hMDVcITB+FeE9SdAEDqfGyJ700O7kCrJlQ+ODXFXTgQzL3FBqXFRPSat/VgsedaZT1uQSTaUHPYRmpncQ2DBWfdCoIYpKKYeDhPB8gtTDkDpknQ4QC+4E2PvUUGK1oozMdY2IQWxMsatzbcUc/WPu2g4AyWXnxi74GqpvVe9ol3tEV7UiTdsPUPS9D/iZc9nzUDF7xkXCkeRr1WUrUxq9WTpXoLBOFr5k42L4PHdFwS2blE+wP4SaUzsSyS6lZc66nR1wqUI8uFamyBZnKAvsvar1grGXsZ6QpRovJms3lx27dM7P/3B4VyXaNcL/yS0v8DINHLoLgtgAM4aLdcEnIdzwMX/3xuuH+PfShdNaFGK17iamifhx8CVBTrMYDgWsp+usTSiRZ3/A6IpF+3dAo+nV1rf1+C01CLeJZUqHglpXZn5XP0IIA3/au7bhRsUGHklVDWPQ9K6w0EhzJ2HpCChXNBiH7iRYrfih4eUOoHXAZQXBy/RA3yUEPbv5uPAonJgcbclNW9ME8FCVsmWEVVyIrxNIs0FsMEOxQmRT4ZUxpdh2+56TDTfYrssNw+JRGcl/Un5fhyC/R3ENe7xYmLnz3sGEyWfzmlUOb6PniGvqcI+y016WROcwOnFSLFEpFweHQm/W5HVWTRM2jDSc05V17i100ES80GQpFho/2vNSZdFwpck69Dc0scLJm6v6tZf8+gKTIQ1eX7Va1CCj+wojDXbLKlKdzud84IO1UxgizKqCuII8yBeMqHkaUSJZgiErKfO/C6Wpep8AD8sQOJ788ry0R2IoyJwsdj7fHp9dSj4Mh9AA9ZAouNWTNXv0AcGUfYy7RwrweV86dPNDuyth4/rA34IF72QMCp9prADkUzt+0zMG4bhkgWTwViQaHKu4EZIrq4GNwl3g1Z0N+nHx3xnrRAatL/DzimxpXkjq/T7Q6mHvO6on/EzZ+1dXhup/kek/iUvzwQ8bH2M4qtAtm9yvqYqChDyXBEOcGkIf/Yn9aEcNgqRa6pP2GKdzdrKoyiYAn4akMuE03iqh4zvO98SVcwWSu4a1ELb6nyX2vLhY2931Kq9CRIusozYSDbCuVoRohZjExEZO9l2Ihy6ok4x9MZLu+UP5WvQakLTuyR21FIdnI7J4yQHnwIBiwx+me2sCD+IEFTE80mmHZo0YHuBZq/O1eyaER0gZH1JKbVC+3KKGMs03w==
  template:
    metadata:
      name: alertmanager-config
      namespace: monitoring
