apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: deadend
      routes:
      - receiver: slack
        matchers:
        - alertname=~"WordpressMysqlDown|WordpressPhpMyAdminDown|WordpressSiteDown"
    receivers:
    - name: slack
      slack_configs:
      - channel: '#tmt-site-monitoring'
        send_resolved: true
        username: 'Alertmanager'
        api_url: 'https://hooks.slack.com/services/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'
    - name: deadend
