apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-backup
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 10Gi